theme = "nightfox"

[editor]
line-number = "relative"
rulers = [100]
color-modes = true

# Show hidden/dotfiles in the file picker.
[editor.file-picker]
hidden = false

[keys.normal]
"C-b" = ":sh pdflatex -interaction=nonstopmode -output-directory=output main.tex"
